<!--#include file = "../lib/utility.asp"-->
<!--#include file = "../lib/aspJSON1.19.asp"-->
<!--#include file = "./connection/db.asp"-->
<%

    JsonStr = getJsonFromReq()
 
    On Error Resume Next
    
    Set oJSON = New aspJSON
    oJSON.loadJSON(JsonStr)

    Json_res = ""
    
    If Err.Number <> 0 Then
        
        On Error Goto 0 
    Else 
    
    custcode = oJSON.data("33072")
    kcepart = oJSON.data("3XT002M06820")

    sql = "SELECT * FROM [Base_Process].[dbo].[FOI_Master]  " 
 
    row = db.execute(sql)
 
    Json_res =  Json_res & "{"
        Json_res =  Json_res & """ID"": """ & row("ID") & ""","
        Json_res =  Json_res & """KCEPART"": """ & row("KCEPART") &  ""","
        Json_res =  Json_res & """REV"": """ & row("REV")& ""","
        Json_res =  Json_res & """CustCode"": """ & row("CustCode")& ""","
        Json_res =  Json_res & """CustPart"": """ & row("CustPart")& ""","
        Json_res =  Json_res & """Surface"": """ & row("Surface")& ""","
        Json_res =  Json_res & """BoardProfile"": """ & row("BoardProfile")& ""","
        Json_res =  Json_res & """LayerCopper"": """ & row("LayerCopper")& ""","
        Json_res =  Json_res & """Core"": """ & row("Core")& ""","
        Json_res =  Json_res & """LMCF_Brand"": """ & row("LMCF_Brand")& ""","
        Json_res =  Json_res & """LMCF_TG"": """ & row("LMCF_TG")& ""","
        Json_res =  Json_res & """LMCF_CuFoil"": """ & row("LMCF_CuFoil")& ""","
        Json_res =  Json_res & """FSBT_Spec"": """ & row("FSBT_Spec")& ""","
        Json_res =  Json_res & """FSBT_MinMax"": """ & row("FSBT_MinMax")& ""","
        Json_res =  Json_res & """FSBT_Unit"": """ & row("FSBT_Unit")& ""","
        Json_res =  Json_res & """SM_CS"": """ & row("SM_CS")& ""","
        Json_res =  Json_res & """SM_SS"": """ & row("SM_SS")& ""","
        Json_res =  Json_res & """SM_NA"": """ & row("SM_NA")& ""","
        Json_res =  Json_res & """SM_Color"": """ & row("SM_Color")& ""","
        Json_res =  Json_res & """SM_Brand"": """ & row("SM_Brand")& ""","
        Json_res =  Json_res & """LP_CS"": """ & row("LP_CS")& ""","
        Json_res =  Json_res & """LP_SS"": """ & row("LP_SS")& ""","
        Json_res =  Json_res & """LP_NA"": """ & row("LP_NA")& ""","
        Json_res =  Json_res & """LP_Color"": """ & row("LP_Color")& ""","
        Json_res =  Json_res & """LP_Brand"": """ & row("LP_Brand")& ""","
        Json_res =  Json_res & """CBI_CS"": """ & row("CBI_CS")& ""","
        Json_res =  Json_res & """CBI_SS"": """ & row("CBI_SS")& ""","
        Json_res =  Json_res & """CBI_NA"": """ & row("CBI_NA")& ""","
        Json_res =  Json_res & """CBI_Color"": """ & row("CBI_Color")& ""","
        Json_res =  Json_res & """CBI_Brand"": """ & row("CBI_Brand")& ""","
        Json_res =  Json_res & """PB_CS"": """ & row("PB_CS")& ""","
        Json_res =  Json_res & """PB_SS"": """ & row("PB_SS")& ""","
        Json_res =  Json_res & """PB_NA"": """ & row("PB_NA")& ""","
        Json_res =  Json_res & """PB_Color"": """ & row("PB_Color")& ""","
        Json_res =  Json_res & """PB_Brand"": """ & row("PB_Brand")& ""","
        Json_res =  Json_res & """UL_CS"": """ & row("UL_CS")& ""","
        Json_res =  Json_res & """UL_SS"": """ & row("UL_SS")& ""","
        Json_res =  Json_res & """UL_PrintOn"": """ & row("UL_PrintOn") & ""","
        Json_res =  Json_res & """UL_Logo"": """ & row("UL_Logo")& ""","
        Json_res =  Json_res & """DC_CS"": """ & row("DC_CS")& ""","
        Json_res =  Json_res & """DC_SS"": """ & row("DC_SS")& ""","
        Json_res =  Json_res & """DC_DC"": """ & row("DC_DC")& ""","
        Json_res =  Json_res & """DC_PrintOn"": """ & row("DC_PrintOn")& ""","
        Json_res =  Json_res & """ET_Edge"": """ & row("ET_Edge")& ""","
        Json_res =  Json_res & """ET_Stamp"": """ & row("ET_Stamp")& ""","
        Json_res =  Json_res & """ET_CS"": """ & row("ET_CS")& ""","
        Json_res =  Json_res & """ET_SS"": """ & row("ET_SS")& ""","
        Json_res =  Json_res & """CustOnBoard"": """ & row("CustOnBoard")& ""","
        Json_res =  Json_res & """KCEOnBoard"": """ & row("KCEOnBoard")& ""","
        Json_res =  Json_res & """DCControl"": """ & row("DCControl")& ""","
        Json_res =  Json_res & """ST_Single"": """ & row("ST_Single")& ""","
        Json_res =  Json_res & """ST_Mulity"": """ & row("ST_Mulity")& ""","
        Json_res =  Json_res & """ST_Pcs"": """ & row("ST_Pcs")& ""","
        Json_res =  Json_res & """XO_Scrap"": """ & row("XO_Scrap")& ""","
        Json_res =  Json_res & """XO_Qty"": """ & row("XO_Qty")& ""","
        Json_res =  Json_res & """XO_SCMark"": """ & row("XO_SCMark")& ""","
        Json_res =  Json_res & """XO_MarkIDE"": """ & row("XO_MarkIDE")& ""","
        Json_res =  Json_res & """Ionic"": """ & row("Ionic")& ""","
        Json_res =  Json_res & """UgNacl"": """ & row("UgNacl")& ""","
        Json_res =  Json_res & """PS_QtyPack"": """ & row("PS_QtyPack")& ""","
        Json_res =  Json_res & """PS_OneWayBoard"": """ & row("PS_OneWayBoard")& ""","
        Json_res =  Json_res & """PS_VacuumPackPE"": """ & row("PS_VacuumPackPE")& ""","
        Json_res =  Json_res & """PS_DoublePackPE"": """ & row("PS_DoublePackPE")& ""","
        Json_res =  Json_res & """PS_VacuumPackESD"": """ & row("PS_VacuumPackESD")& ""","
        Json_res =  Json_res & """PS_DoublePackESD"": """ & row("PS_DoublePackESD")& ""","
        Json_res =  Json_res & """PS_VacuumNylon"": """ & row("PS_VacuumNylon")& ""","
        Json_res =  Json_res & """PS_DoublePackNylon"": """ & row("PS_DoublePackNylon")& ""","
        Json_res =  Json_res & """PS_Aluminum"": """ & row("PS_Aluminum")& ""","
        Json_res =  Json_res & """PS_DoublePackMBB"": """ & row("PS_DoublePackMBB")& ""","
        Json_res =  Json_res & """PS_SulphurFree"": """ & row("PS_SulphurFree")& ""","
        Json_res =  Json_res & """PS_Siliga"": """ & row("PS_Siliga")& ""","
        Json_res =  Json_res & """PS_RemarkSILICAGEL"": """ & row("PS_RemarkSILICAGEL")& ""","
        Json_res =  Json_res & """PS_HIC"": """ & row("PS_HIC")& ""","
        Json_res =  Json_res & """PS_HIC10"": """ & row("PS_HIC10")& ""","
        Json_res =  Json_res & """PS_Others"": """ & row("PS_Others")& ""","
        Json_res =  Json_res & """PS_OthersRemark"": """ & row("PS_OthersRemark")& ""","
        Json_res =  Json_res & """PL_KCELabel"": """ & row("PL_KCELabel")& ""","
        Json_res =  Json_res & """PL_Rohs6/6"": """ & row("PL_Rohs6/6")& ""","
        Json_res =  Json_res & """PL_CustLabel"": """ & row("PL_CustLabel")& ""","
        Json_res =  Json_res & """PL_SpecialLabel"": """ & row("PL_SpecialLabel")& ""","
        Json_res =  Json_res & """PL_Other"": """ & row("PL_Other")& ""","
        Json_res =  Json_res & """PL_SpecialLabelRemark"": """ & row("PL_SpecialLabelRemark")& ""","
        Json_res =  Json_res & """PL_Rohs"": """ & row("PL_Rohs")& ""","
        Json_res =  Json_res & """PL_PackingRemark"": """ & row("PL_PackingRemark")& ""","
        Json_res =  Json_res & """CT_Material"": """ & row("CT_Material")& ""","
        Json_res =  Json_res & """CT_Weight"": """ & row("CT_Weight")& ""","
        Json_res =  Json_res & """CL_KCELabel"": """ & row("CL_KCELabel")& ""","
        Json_res =  Json_res & """CL_Rohs6/6"": """ & row("CL_Rohs6/6")& ""","
        Json_res =  Json_res & """CL_CustLabel"": """ & row("CL_CustLabel")& ""","
        Json_res =  Json_res & """CL_SpecialLabel"": """ & row("CL_SpecialLabel")& ""","
        Json_res =  Json_res & """CL_Other"": """ & row("CL_Other")& ""","
        Json_res =  Json_res & """CL_SpecialLabelRemark"": """ & row("CL_SpecialLabelRemark")& ""","
        Json_res =  Json_res & """CL_Rohs"": """ & row("CL_Rohs")& ""","
        Json_res =  Json_res & """QA_CofC"": """ & row("QA_CofC")& ""","
        Json_res =  Json_res & """QA_INS_FA"": """ & row("QA_INS_FA")& ""","
        Json_res =  Json_res & """QA_PHOTO"": """ & row("QA_PHOTO")& ""","
        Json_res =  Json_res & """QA_MICRO"": """ & row("QA_MICRO")& ""","
        Json_res =  Json_res & """QA_Pcs"": """ & row("QA_Pcs")& ""","
        Json_res =  Json_res & """QA_SampleBoardTest"": """ & row("QA_SampleBoardTest")& ""","
        Json_res =  Json_res & """QA_Test"": """ & row("QA_Test")& ""","
        Json_res =  Json_res & """QA_SampleBoardNotTest"": """ & row("QA_SampleBoardNotTest")& ""","
        Json_res =  Json_res & """QA_NotTest"": """ & row("QA_NotTest")& ""","
        Json_res =  Json_res & """QA_PPAP"": """ & row("QA_PPAP")& ""","
        Json_res =  Json_res & """QA_Level"": """ & row("QA_Level")& ""","
        Json_res =  Json_res & """QA_SolderTest"": """ & row("QA_SolderTest")& ""","
        Json_res =  Json_res & """QA_SPC"": """ & row("QA_SPC")& ""","
        Json_res =  Json_res & """QA_Other"": """ & row("QA_Other")& ""","
        Json_res =  Json_res & """QA_OtherRequirement"": """ & row("QA_OtherRequirement")& ""","
        Json_res =  Json_res & """QA_SpecialNote"": """ & row("QA_SpecialNote")& ""","
        Json_res =  Json_res & """DocCheck_CUTHK"": """ & row("DocCheck_CUTHK")& ""","
        Json_res =  Json_res & """DocCheck_SMTHK"": """ & row("DocCheck_SMTHK")& ""","
        Json_res =  Json_res & """DocCheck__SFTHK"": """ & row("DocCheck__SFTHK")& ""","
        Json_res =  Json_res & """RemarkDC"": """ & row("RemarkDC")& ""","
        Json_res =  Json_res & """Prepreg"": """ & row("Prepreg")& ""","
        Json_res =  Json_res & """Laminate "": """ & row("Laminate ")& ""","
        Json_res =  Json_res & """RD_COFC"": """ & row("RD_COFC")& ""","
        Json_res =  Json_res & """RD_INS/FA"": """ & row("RD_INS/FA")& ""","
        Json_res =  Json_res & """RD_SPC"": """ & row("RD_SPC")& ""","
        Json_res =  Json_res & """RD_PPAP"": """ & row("RD_PPAP")& ""","
        Json_res =  Json_res & """RD_PHOTO"": """ & row("RD_PHOTO")& ""","
        Json_res =  Json_res & """RD_SOLDER"": """ & row("RD_SOLDER")& ""","
        Json_res =  Json_res & """UpdateDate"": """ & row("UpdateDate")& ""","
        Json_res =  Json_res & """UpdateBy"": """ & row("UpdateBy")& ""","
        Json_res =  Json_res & """CustName"": """ & row("CustName") & """"
    Json_res =  Json_res & "}"
    End If
    
    Response.Write Json_res

%>